server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: restaurantModule
          uri: lb://RESTAURANT-SERVICE
          predicates:
            - Path=/restaurants/**, /menus/**, /foods/**
        - id: orderModule
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/orders/**
        - id: paymentModule
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payments/**
        - id: userModule
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**